name: advanced_login_app
description: An advanced immersive login application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.0
  flutter_animate: ^4.5.2  # Downgrade to fix animation issues
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  http: ^1.6.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.1.0
  provider: ^6.1.1
  confetti: ^0.8.0
  lottie: ^3.3.2
  image_picker: ^0.8.7+4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
